[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-socketio>=5.5.1",
    "flask==3.1.0",
    "eventlet>=0.40.0",
]
