services:
  - type: web
    name: poker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 main:application
    rootDir: your_project
