services:
  - type: web
    name: poker-backend
    env: python
    buildCommand: "pip install -r main/Create-Repl/your_project/requirements.txt"
    startCommand: "python main/Create-Repl/your_project/main.py"
